from Seq1 import Seq
print("---|PRACTICE 1: EXERCISE 7|---")
DNA_bases = ["A", "C", "T", "G"]
s1 = Seq("ACTGA")
s2 = Seq()
s3 = Seq("ACTXG")
print("Sequence" + str(1) + ": (Length: " + str(s1.len()) + ") " + str(s1))
print("  Bases:", s1.count_base())
print("  Rev:", s1.seq_reverse())
print("Sequence" + str(2) + ": (Length: " + str(s2.len()) + ") " + str(s2))
print("  Bases:", s2.count_base())
print("  Rev:", s2.seq_reverse())
print("Sequence" + str(3) + ": (Length: " + str(s3.len()) + ") " + str(s3))
print("  Bases:", s3.count_base())
print("  Rev:", s3.seq_reverse())
